name: "Pull Request Labeler"
on:
  # Do not use pull_request_target with actions/cache or actions/checkout.
  pull_request_target:

permissions: { }

jobs:
  labeler:
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/labeler@v5
